### PR TITLE
add attachmment .path to xml entry as a fallback for automatic attachment

### PR DESCRIPTION
**Pull request by Iv3x**
hi,

do you think this could be a solution for adding the path/extension to the report xml ? 
I actually dont know if this an problem from the server version of xray, but for me I actually get attachments without any extension/filetype. This actually results in Screenshots that cant be opened in the test execution in jira. 

this was an Solution by @mxschmitt that he actually added in a PR that was closed since pw team decided an extra reporter for xray would be better: https://github.com/microsoft/playwright/pull/22443/files 

I can try to add tests and additions if needed to help :-)

### CODE REVIEW

**Comment by bitcoder** [comment]
Hi, thanks for this.
This is currently a problem in Xray as missing extension then makes the screenshots not previewable from the UI.
Would this solve this reported issue  https://github.com/microsoft/playwright/issues/22396 ?
We also need to make it work whenever we are adding attachments inline (not from files), i.e. using the `body` attribute instead of the  `path` attributte:

https://github.com/Xray-App/playwright-junit-reporter/blob/4ec6b8cd20bafc8dcec5cf466eded69cc80083ca/tests/reporter-junit.spec.ts#L414

**Comment by Iv3x** [comment]
hi,
exactly this would solve the issue. I also just wrote a little dirty script dealing with this in the 2-3 days ago 😅. that just adds the extensions for video, screenshot etc

true getting it from the content type would be more cleaner then the path.
I try to take a look into this.

**Comment by Iv3x** [comment]
okay so i checked actually the attachment and thats actually the object generated by the screenshot method on failure:
```
{
  name: 'screenshot',
  path: '/foo/test-failed-1.png',
  contentType: 'image/png',
  body: undefined
}
```

so a solution could be adding a mapper that can map the type to the correct ext that can be called when we try to add the right the file extension to the attachment name:

something like:
const attachmentName = attachment.name + getFileContentType(); /// returns .txt, webm etc.

I try to write a small class for this

**Comment by Iv3x** [comment]
@bitcoder I added a mapper class that actually adds the default ending to attachments that actually have just a name. 
do you think thats an kinda okay solution for now ?

**Comment by bitcoder** [comment]
> @bitcoder I added a mapper class that actually adds the default ending to attachments that actually have just a name without an ending. do you think thats an kinda okay solution for now ?

thanks!
I think so. I need some time to validate this as I have other things going on

**Comment by Iv3x** [comment]
> > @bitcoder I added a mapper class that actually adds the default ending to attachments that actually have just a name without an ending. do you think thats an kinda okay solution for now ?
> 
> thanks! I think so. I need some time to validate this as I have other things going on

great :-) i added some polishing to the class. Just let me know if you think we should have more tests for this or something

**Comment by bitcoder** [comment]
I'm waiting for internal feedback on licensing; I'll come back here whenever I have feedback.

**Comment by kevinruhland** [comment]
Is there any update regarding the licensing ? We are having the same issue with our installation.

**Comment by bitcoder** [comment]
Yes. I just need to have some time to pick this which I don't have right now

**Pull request merged**
